package com.jmwl.gostudio.ui.dialogs.editor

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.background
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.OutlinedTextFieldDefaults
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.jmwl.gostudio.plugins.plugin_tool_def
import com.jmwl.gostudio.tools.tool_engine
import com.jmwl.gostudio.ui.theme.app_theme_provider
import com.jmwl.gostudio.ui.toast.app_toast
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

/**
 * 插件工具通用弹窗：输入 → 宿主内置引擎转换 → 输出预览 + 复制到剪贴板。
 * 选项区按 kind 定制（当前内置：json-to-go 的结构体名称）。
 * 配置（结构体名、上次输入）持久化在插件目录 config.json，由宿主代存。
 */
@Composable
fun editor_tool_dialog(
    tool_def: plugin_tool_def,
    on_dismiss: () -> Unit
) {
    val colors = app_theme_provider.colors
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    val clipboard = remember(context) {
        context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
    }

    // 插件私有配置：plugins/<plugin_id>/config.json（内置插件升级覆盖目录时由宿主保留）
    val config_file = remember(tool_def.plugin_id) {
        com.jmwl.gostudio.plugins.plugin_manager.dir_of(tool_def.plugin_id)
            ?.let { dir -> java.io.File(dir, "config.json") }
    }
    val saved_config = remember(tool_def.key) { load_tool_config(config_file) }

    var input by remember(tool_def.key) {
        mutableStateOf(saved_config?.optString("last_input").orEmpty())
    }
    var struct_name by remember(tool_def.key) {
        mutableStateOf(
            saved_config?.optString("struct_name")?.takeIf { it.isNotBlank() } ?: "AutoGenerated"
        )
    }
    var output by remember(tool_def.key) { mutableStateOf("") }
    var error_text by remember(tool_def.key) { mutableStateOf<String?>(null) }
    var converting by remember { mutableStateOf(false) }
    val is_json_tool = tool_def.kind == tool_engine.KIND_JSON_TO_GO

    fun save_config() {
        val file = config_file ?: return
        scope.launch(Dispatchers.IO) {
            runCatching {
                val json = org.json.JSONObject()
                    .put("struct_name", struct_name)
                    .put("last_input", input.take(100_000))
                file.writeText(json.toString())
            }
        }
    }

    fun dismiss() {
        save_config()
        on_dismiss()
    }

    fun do_convert() {
        if (converting) return
        converting = true
        error_text = null
        output = ""
        scope.launch {
            val options = if (is_json_tool) mapOf("struct_name" to struct_name) else emptyMap()
            val result = withContext(Dispatchers.Default) {
                tool_engine.run(tool_def.kind, input, options)
            }
            converting = false
            result.fold(
                onSuccess = {
                    output = it
                    save_config()
                },
                onFailure = { error_text = it.message ?: "转换失败" }
            )
        }
    }

    AlertDialog(
        onDismissRequest = { dismiss() },
        containerColor = colors.dialog_bg,
        shape = RoundedCornerShape(14.dp),
        title = {
            Text(
                text = tool_def.name,
                color = colors.dialog_text,
                fontSize = 17.sp,
                fontWeight = FontWeight.Medium
            )
        },
        text = {
            Column(verticalArrangement = Arrangement.spacedBy(9.dp)) {
                val input_colors = OutlinedTextFieldDefaults.colors(
                    focusedBorderColor = colors.dialog_input_border,
                    unfocusedBorderColor = colors.dialog_input_hint.copy(alpha = 0.5f),
                    focusedTextColor = colors.dialog_input_text,
                    unfocusedTextColor = colors.dialog_input_text,
                    cursorColor = colors.dialog_input_border,
                    focusedContainerColor = colors.dialog_input_bg,
                    unfocusedContainerColor = colors.dialog_input_bg
                )

                if (is_json_tool) {
                    OutlinedTextField(
                        value = struct_name,
                        onValueChange = { struct_name = it },
                        singleLine = true,
                        placeholder = { Text("结构体名称", color = colors.dialog_input_hint) },
                        colors = input_colors,
                        textStyle = androidx.compose.ui.text.TextStyle(
                            fontFamily = FontFamily.Monospace,
                            fontSize = 13.sp
                        ),
                        modifier = Modifier.fillMaxWidth()
                    )
                }

                OutlinedTextField(
                    value = input,
                    onValueChange = { input = it },
                    placeholder = { Text("粘贴 JSON…", color = colors.dialog_input_hint) },
                    colors = input_colors,
                    textStyle = androidx.compose.ui.text.TextStyle(
                        fontFamily = FontFamily.Monospace,
                        fontSize = 12.sp
                    ),
                    modifier = Modifier
                        .fillMaxWidth()
                        .heightIn(min = 112.dp, max = 200.dp)
                )

                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    OutlinedButton(
                        enabled = !converting,
                        onClick = {
                            val pasted = clipboard.primaryClip
                                ?.getItemAt(0)
                                ?.coerceToText(context)
                                ?.toString()
                                .orEmpty()
                            if (pasted.isNotBlank()) {
                                input = pasted
                                error_text = null
                            } else {
                                app_toast.show(context, "剪贴板为空", app_toast.LENGTH_SHORT)
                            }
                        }
                    ) {
                        Text("粘贴", color = colors.dialog_text, fontSize = 13.sp)
                    }
                    OutlinedButton(
                        enabled = !converting && input.isNotBlank(),
                        onClick = { do_convert() }
                    ) {
                        Text(
                            if (converting) "转换中…" else "转换",
                            color = colors.dialog_clone_bg,
                            fontSize = 13.sp
                        )
                    }
                }

                error_text?.let { message ->
                    Text(
                        text = message,
                        color = colors.danger,
                        fontSize = 12.sp,
                        fontFamily = FontFamily.Monospace
                    )
                }

                if (output.isNotBlank()) {
                    Column(
                        modifier = Modifier
                            .fillMaxWidth()
                            .heightIn(max = 220.dp)
                            .clip(RoundedCornerShape(8.dp))
                            .background(colors.editor_bg)
                            .verticalScroll(rememberScrollState())
                    ) {
                        Text(
                            text = output,
                            color = colors.editor_text,
                            fontSize = 11.sp,
                            fontFamily = FontFamily.Monospace,
                            modifier = Modifier.fillMaxWidth()
                        )
                    }
                }
            }
        },
        confirmButton = {
            TextButton(
                enabled = output.isNotBlank(),
                onClick = {
                    clipboard.setPrimaryClip(ClipData.newPlainText(tool_def.name, output))
                    app_toast.show(context, "已复制到剪贴板", app_toast.LENGTH_SHORT)
                }
            ) {
                Text("复制到剪贴板", color = if (output.isNotBlank()) colors.dialog_clone_bg else colors.dialog_hint)
            }
        },
        dismissButton = {
            TextButton(onClick = { dismiss() }) {
                Text("关闭", color = colors.dialog_hint)
            }
        }
    )
}

/** 读取插件工具配置（不存在/损坏返回 null） */
private fun load_tool_config(file: java.io.File?): org.json.JSONObject? {
    if (file == null || !file.isFile) return null
    return runCatching { org.json.JSONObject(file.readText()) }.getOrNull()
}
