package com.jmwl.gostudio.tools

/**
 * JSON → Go 结构体转换器（宿主内置工具引擎，纯 Kotlin，离线可用）。
 *
 * 能力对齐 mholt/json-to-go 的常用行为：
 * - 类型推断：string / bool / int（Int 范围内）/ int64 / float64 / any（null 或冲突类型）
 * - 嵌套对象 → 内联匿名 struct；数组元素为对象时跨元素合并字段（联合类型）
 * - 数字类型看原始字面量：`1` → int、`1.0` → float64（解析树保留 raw 文本）
 * - 字段名：snake/kebab/空格分隔转导出的 CamelCase，重名自动加序号
 * - 始终输出 json tag（保留原始 key，非法字符转义）
 * - 缩进 tab、列对齐空格，多行内联 struct 断开对齐块（与 gofmt 的 tabwriter 行为一致）
 *
 * 解析器在标准 JSON 之上做了一点容错：允许尾逗号、单引号字符串、裸键名，
 * 方便从日志/JS 代码里直接粘贴。
 */
object json_to_go_converter {

    /** 入口：JSON 文本 → Go 结构体定义。根节点必须是对象或数组。 */
    fun convert(json_text: String, struct_name: String = "AutoGenerated"): Result<String> = runCatching {
        if (json_text.isBlank()) throw IllegalArgumentException("请输入 JSON 内容")
        val root = json_parser(json_text).parse()
        val type = assign_names(infer(root))
        val name = sanitize_struct_name(struct_name)
        when (type) {
            is go_struct -> "type $name ${render_struct(type, 0)}"
            is go_slice -> "type $name []${render(type.elem, 0)}"
            else -> throw IllegalArgumentException("根节点必须是 JSON 对象或数组")
        }
    }

    // ---------- 类型树 ----------

    private sealed class go_type
    private object go_null : go_type()        // 值为 null（合并时透明，渲染退化为 any）
    private object go_any : go_type()
    private object go_string : go_type()
    private object go_bool : go_type()
    private object go_float : go_type()       // float64
    private object go_int : go_type()         // int
    private object go_int64 : go_type()       // int64
    private data class go_slice(val elem: go_type) : go_type()
    private data class go_struct(val fields: List<go_field>) : go_type()
    private data class go_field(val name: String, val tag_key: String, val type: go_type)

    // ---------- 推断 ----------

    private fun infer(node: json_node): go_type = when (node) {
        is json_string_node -> go_string
        is json_bool_node -> go_bool
        is json_null_node -> go_null
        is json_number_node -> infer_number(node.raw)
        is json_array_node -> go_slice(unify_all(node.items))
        is json_object_node -> go_struct(
            node.entries.map { (key, value) -> go_field("", key, infer(value)) }
        )
    }

    /** 数字看原始字面量：带小数点/指数 → float64；整数按范围 int/int64；超 Long 退化 float64 */
    private fun infer_number(raw: String): go_type {
        if (raw.contains('.') || raw.contains('e') || raw.contains('E')) return go_float
        return raw.toLongOrNull()
            ?.let { if (it in Int.MIN_VALUE..Int.MAX_VALUE) go_int else go_int64 }
            ?: go_float
    }

    /** 数组元素类型合并：全部为 null → go_null（渲染为 any）；跨元素对象合并字段 */
    private fun unify_all(items: List<json_node>): go_type {
        var result: go_type? = null
        for (item in items) result = unify_nullable(result, infer(item))
        return result ?: go_any
    }

    private fun unify_nullable(a: go_type?, b: go_type): go_type = a?.let { unify(it, b) } ?: b

    private fun unify(a: go_type, b: go_type): go_type = when {
        a == b -> a
        a == go_null -> b
        b == go_null -> a
        a is go_struct && b is go_struct -> merge_structs(a, b)
        a is go_slice && b is go_slice -> go_slice(unify(a.elem, b.elem))
        is_number(a) && is_number(b) -> when {
            a == go_float || b == go_float -> go_float
            a == go_int64 || b == go_int64 -> go_int64
            else -> go_int
        }
        else -> go_any
    }

    private fun is_number(type: go_type) =
        type == go_int || type == go_int64 || type == go_float

    /** 跨数组元素合并对象：按原始 key 对齐，同 key 类型再合并；保持首次出现顺序 */
    private fun merge_structs(a: go_struct, b: go_struct): go_struct {
        val merged = LinkedHashMap<String, go_field>()
        a.fields.forEach { merged[it.tag_key] = it }
        for (field in b.fields) {
            val existing = merged[field.tag_key]
            merged[field.tag_key] = if (existing == null) {
                field
            } else {
                go_field(existing.name, field.tag_key, unify(existing.type, field.type))
            }
        }
        return go_struct(merged.values.toList())
    }

    // ---------- 命名 ----------

    /** 渲染前统一分配导出字段名（合并可能引入跨对象的重名，这里按 struct 去重） */
    private fun assign_names(type: go_type): go_type = when (type) {
        is go_struct -> {
            val used = mutableMapOf<String, Int>()
            go_struct(
                type.fields.map { field ->
                    val base = field_name(field.tag_key)
                    val count = used[base] ?: 0
                    used[base] = count + 1
                    val name = if (count == 0) base else "${base}_${count + 1}"
                    go_field(name, field.tag_key, assign_names(field.type))
                }
            )
        }
        is go_slice -> go_slice(assign_names(type.elem))
        else -> type
    }

    /** key → 导出的 Go 字段名：按 _ - . 空格切词逐词首字母大写；数字开头加 Num 前缀 */
    private fun field_name(key: String): String {
        val words = key.split('_', '-', '.', ' ', '\t').filter { it.isNotEmpty() }
        var name = if (words.isEmpty()) {
            "Field"
        } else {
            words.joinToString("") { word ->
                word.filter { it.isLetterOrDigit() || it == '_' }
                    .replaceFirstChar { if (it.isLetter()) it.uppercaseChar() else it }
            }
        }
        name = name.trimStart('_')
        if (name.isEmpty()) name = "Field"
        if (name.first().isDigit()) name = "Num$name"
        return name
    }

    /** 用户输入的结构体名 → 合法导出标识符 */
    private fun sanitize_struct_name(input: String): String {
        val cleaned = input.trim().split('_', '-', '.', ' ', '\t')
            .filter { it.isNotEmpty() }
            .joinToString("") { word ->
                word.filter { it.isLetterOrDigit() }
                    .replaceFirstChar { if (it.isLetter()) it.uppercaseChar() else it }
            }
        if (cleaned.isEmpty()) return "AutoGenerated"
        return if (cleaned.first().isDigit()) "Num$cleaned" else cleaned
    }

    /** json tag 内的原始 key 转义（Go 字符串语法与 JSON 在这几个字符上一致） */
    private fun escape_tag(key: String): String {
        val sb = StringBuilder()
        for (c in key) when {
            c == '\\' -> sb.append("\\\\")
            c == '"' -> sb.append("\\\"")
            c < ' ' -> sb.append("\\u%04x".format(c.code))
            else -> sb.append(c)
        }
        return sb.toString()
    }

    // ---------- 渲染 ----------

    private fun render(type: go_type, depth: Int): String = when (type) {
        go_null, go_any -> "any"
        go_string -> "string"
        go_bool -> "bool"
        go_float -> "float64"
        go_int -> "int"
        go_int64 -> "int64"
        is go_slice -> "[]" + render(type.elem, depth)
        is go_struct -> render_struct(type, depth)
    }

    private class rendered_field(
        val name: String,
        val type_lines: List<String>,
        val tag: String
    ) {
        val multiline: Boolean get() = type_lines.size > 1
    }

    /**
     * 渲染 struct 体（不含前导缩进的 `struct {`，收尾 `}` 缩进到 depth）。
     * 字段名列对齐全 struct 生效；类型/标签列只在「连续单行类型」块内对齐，
     * 多行内联 struct 断块（对齐 gofmt 的 tabwriter 行为）。
     */
    private fun render_struct(struct: go_struct, depth: Int): String {
        if (struct.fields.isEmpty()) return "struct{}"

        val indent = "\t".repeat(depth)
        val inner_indent = "\t".repeat(depth + 1)
        val fields = struct.fields.map { field ->
            rendered_field(
                name = field.name,
                type_lines = render(field.type, depth + 1).split('\n'),
                tag = "`json:\"${escape_tag(field.tag_key)}\"`"
            )
        }
        val name_width = fields.maxOf { it.name.length }

        val sb = StringBuilder("struct {\n")
        var i = 0
        while (i < fields.size) {
            val field = fields[i]
            if (field.multiline) {
                sb.append(inner_indent)
                    .append(field.name.padEnd(name_width)).append(' ')
                    .append(field.type_lines.first()).append('\n')
                // 中间行自带缩进；最后一行是内联 struct 的 `}`，标签跟一个空格
                for (line_index in 1 until field.type_lines.size - 1) {
                    sb.append(field.type_lines[line_index]).append('\n')
                }
                sb.append(field.type_lines.last()).append(' ').append(field.tag).append('\n')
                i++
            } else {
                // 连续单行字段成块，块内按最长类型对齐标签
                var end = i
                while (end < fields.size && !fields[end].multiline) end++
                val type_width = fields.subList(i, end).maxOf { it.type_lines.first().length }
                for (single in fields.subList(i, end)) {
                    sb.append(inner_indent)
                        .append(single.name.padEnd(name_width)).append(' ')
                        .append(single.type_lines.first().padEnd(type_width)).append(' ')
                        .append(single.tag).append('\n')
                }
                i = end
            }
        }
        sb.append(indent).append('}')
        return sb.toString()
    }
}

// ---------- 轻量 JSON 解析 ----------

/** 解析失败：带行列号，直接展示给用户 */
class json_parse_exception(message: String, val line: Int, val column: Int) :
    Exception("$message（第 $line 行第 $column 列）")

private sealed class json_node
private class json_object_node(val entries: LinkedHashMap<String, json_node>) : json_node()
private class json_array_node(val items: List<json_node>) : json_node()
private class json_string_node(val value: String) : json_node()
private class json_number_node(val raw: String) : json_node()
private class json_bool_node(val value: Boolean) : json_node()
private object json_null_node : json_node()

private class json_parser(private val text: String) {
    private var pos = 0
    private var line = 1
    private var column = 1

    companion object {
        private val number_pattern = Regex("-?\\d+(\\.\\d+)?([eE][+-]?\\d+)?")
    }

    fun parse(): json_node {
        skip_whitespace()
        val node = parse_value()
        skip_whitespace()
        if (pos < text.length) throw error("JSON 结束后有多余内容")
        return node
    }

    private fun skip_whitespace() {
        while (pos < text.length) {
            val c = text[pos]
            if (c == ' ' || c == '\t' || c == '\r' || c == '\n') advance() else break
        }
    }

    private fun advance() {
        if (text[pos] == '\n') {
            line++
            column = 1
        } else {
            column++
        }
        pos++
    }

    private fun peek(): Char? = text.getOrNull(pos)

    private fun error(message: String) = json_parse_exception(message, line, column)

    private fun expect(c: Char) {
        if (peek() == c) advance() else throw error("期望 '$c'，实际是 '${peek() ?: "结束"}'")
    }

    private fun parse_value(): json_node {
        return when (val c = peek()) {
            null -> throw error("JSON 意外结束")
            '{' -> parse_object()
            '[' -> parse_array()
            '"' -> json_string_node(parse_string('"'))
            '\'' -> json_string_node(parse_string('\''))
            't', 'f' -> parse_bool()
            'n' -> parse_null()
            else -> if (c == '-' || c.isDigit()) {
                parse_number()
            } else {
                throw error("非法字符 '$c'")
            }
        }
    }

    private fun parse_object(): json_object_node {
        expect('{')
        val entries = LinkedHashMap<String, json_node>()
        skip_whitespace()
        if (peek() == '}') {
            advance()
            return json_object_node(entries)
        }
        while (true) {
            skip_whitespace()
            val key = when (val c = peek()) {
                null -> throw error("JSON 意外结束")
                '"', '\'' -> parse_string(c)
                else -> if (c.isLetterOrDigit() || c == '_' || c == '$') parse_bare_key()
                else throw error("对象键必须是字符串")
            }
            skip_whitespace()
            expect(':')
            skip_whitespace()
            entries[key] = parse_value()
            skip_whitespace()
            when (peek()) {
                ',' -> {
                    advance()
                    skip_whitespace()
                    // 容错：尾逗号
                    if (peek() == '}') {
                        advance()
                        return json_object_node(entries)
                    }
                }
                '}' -> {
                    advance()
                    return json_object_node(entries)
                }
                null -> throw error("JSON 意外结束（缺少 '}'）")
                else -> throw error("期望 ',' 或 '}'")
            }
        }
    }

    private fun parse_array(): json_array_node {
        expect('[')
        val items = mutableListOf<json_node>()
        skip_whitespace()
        if (peek() == ']') {
            advance()
            return json_array_node(items)
        }
        while (true) {
            skip_whitespace()
            items.add(parse_value())
            skip_whitespace()
            when (peek()) {
                ',' -> {
                    advance()
                    skip_whitespace()
                    // 容错：尾逗号
                    if (peek() == ']') {
                        advance()
                        return json_array_node(items)
                    }
                }
                ']' -> {
                    advance()
                    return json_array_node(items)
                }
                null -> throw error("JSON 意外结束（缺少 ']'）")
                else -> throw error("期望 ',' 或 ']'")
            }
        }
    }

    private fun parse_string(quote: Char): String {
        expect(quote)
        val sb = StringBuilder()
        while (true) {
            when (val c = peek()) {
                null -> throw error("字符串未闭合")
                quote -> {
                    advance()
                    return sb.toString()
                }
                '\\' -> {
                    advance()
                    when (val escaped = peek()) {
                        null -> throw error("字符串未闭合")
                        '"', '\'', '\\', '/' -> {
                            sb.append(escaped)
                            advance()
                        }
                        'b' -> { sb.append('\b'); advance() }
                        'f' -> { sb.append('\u000C'); advance() }
                        'n' -> { sb.append('\n'); advance() }
                        'r' -> { sb.append('\r'); advance() }
                        't' -> { sb.append('\t'); advance() }
                        'u' -> {
                            advance()
                            if (pos + 4 > text.length) throw error("\\u 转义不完整")
                            val hex = text.substring(pos, pos + 4)
                            val code = hex.toIntOrNull(16) ?: throw error("非法的 \\u 转义 '\\u$hex'")
                            repeat(4) { advance() }
                            sb.append(code.toChar())
                        }
                        else -> throw error("非法转义 '\\$escaped'")
                    }
                }
                else -> {
                    if (c < ' ') throw error("字符串含未转义的控制字符")
                    sb.append(c)
                    advance()
                }
            }
        }
    }

    /** 裸键名容错（JS 风格）：字母/数字/下划线/$ 组成，读到 `:` 或空白前 */
    private fun parse_bare_key(): String {
        val start = pos
        while (pos < text.length) {
            val c = text[pos]
            if (c.isLetterOrDigit() || c == '_' || c == '$') advance() else break
        }
        if (pos == start) throw error("对象键不能为空")
        return text.substring(start, pos)
    }

    private fun parse_bool(): json_bool_node {
        if (match_word("true")) return json_bool_node(true)
        if (match_word("false")) return json_bool_node(false)
        throw error("非法字面量")
    }

    private fun parse_null(): json_node {
        if (match_word("null")) return json_null_node
        throw error("非法字面量")
    }

    private fun match_word(word: String): Boolean {
        if (text.regionMatches(pos, word, 0, word.length)) {
            repeat(word.length) { advance() }
            return true
        }
        return false
    }

    private fun parse_number(): json_number_node {
        val start = pos
        advance()
        while (pos < text.length) {
            val c = text[pos]
            if (c.isDigit() || c == '.' || c == 'e' || c == 'E' || c == '+' || c == '-') {
                advance()
            } else {
                break
            }
        }
        val raw = text.substring(start, pos)
        if (!number_pattern.matches(raw)) throw json_parse_exception(
            "非法数字字面量 '$raw'",
            line,
            column
        )
        return json_number_node(raw)
    }
}
