package com.jmwl.gostudio.tools

/**
 * 工具引擎注册表：插件的 tool.json 只声明 kind，具体逻辑由宿主内置实现。
 * 插件保持数据包原则（不执行插件代码），新增 kind 需要随宿主发版。
 */
object tool_engine {

    /** JSON → Go 结构体 */
    const val KIND_JSON_TO_GO = "json-to-go"

    /** 当前宿主支持的 kind 集合（供 enabled_tools 过滤） */
    val supported_kinds: Set<String> = setOf(KIND_JSON_TO_GO)

    /**
     * 执行工具转换。
     * @param options 工具选项，如 json-to-go 的 struct_name
     */
    fun run(kind: String, input: String, options: Map<String, String> = emptyMap()): Result<String> {
        return when (kind) {
            KIND_JSON_TO_GO -> json_to_go_converter.convert(
                json_text = input,
                struct_name = options["struct_name"]?.takeIf { it.isNotBlank() } ?: "AutoGenerated"
            )
            else -> Result.failure(UnsupportedOperationException("未知工具类型: $kind"))
        }
    }
}
