package com.jmwl.gostudio.tools

import com.google.common.truth.Truth.assertThat
import org.junit.Test

/**
 * JSON → Go 结构体转换器回归：
 * 输出的代码用户会直接粘贴进项目，类型推断/命名/格式任何回退都是坏体验，
 * 这里锁住各关键路径的精确输出。
 */
class json_to_go_converter_test {

    private fun convert(json: String, struct_name: String = "AutoGenerated"): String =
        json_to_go_converter.convert(json, struct_name).getOrThrow()

    @Test
    fun `basic scalars with tags`() {
        val out = convert(
            """{"name": "GoStudio", "stars": 128, "score": 4.9, "active": true, "note": null, "user_name": "yitong"}"""
        )
        assertThat(out).isEqualTo(
            listOf(
                "type AutoGenerated struct {",
                "\tName     string  `json:\"name\"`",
                "\tStars    int     `json:\"stars\"`",
                "\tScore    float64 `json:\"score\"`",
                "\tActive   bool    `json:\"active\"`",
                "\tNote     any     `json:\"note\"`",
                "\tUserName string  `json:\"user_name\"`",
                "}"
            ).joinToString("\n")
        )
    }

    @Test
    fun `nested object inlines struct and breaks alignment`() {
        val out = convert("""{"id": 1, "author": {"name": "y", "vip": true}}""")
        assertThat(out).isEqualTo(
            listOf(
                "type AutoGenerated struct {",
                "\tId     int `json:\"id\"`",
                "\tAuthor struct {",
                "\t\tName string `json:\"name\"`",
                "\t\tVip  bool   `json:\"vip\"`",
                "\t} `json:\"author\"`",
                "}"
            ).joinToString("\n")
        )
    }

    @Test
    fun `array of objects merges fields across elements`() {
        val out = convert("""{"items": [{"a": 1, "b": "x"}, {"a": 2.5, "c": true}]}""")
        assertThat(out).isEqualTo(
            listOf(
                "type AutoGenerated struct {",
                "\tItems []struct {",
                "\t\tA float64 `json:\"a\"`",
                "\t\tB string  `json:\"b\"`",
                "\t\tC bool    `json:\"c\"`",
                "\t} `json:\"items\"`",
                "}"
            ).joinToString("\n")
        )
    }

    @Test
    fun `field name collisions and digit-leading keys`() {
        val out = convert(
            """{"user name": 1, "user_name": 2, "2fa": true, "id": [1, "a"]}"""
        )
        assertThat(out).isEqualTo(
            listOf(
                "type AutoGenerated struct {",
                "\tUserName   int   `json:\"user name\"`",
                "\tUserName_2 int   `json:\"user_name\"`",
                "\tNum2fa     bool  `json:\"2fa\"`",
                "\tId         []any `json:\"id\"`",
                "}"
            ).joinToString("\n")
        )
    }

    @Test
    fun `root array produces slice of struct`() {
        val out = convert("""[{"x": 1}]""")
        assertThat(out).isEqualTo(
            listOf(
                "type AutoGenerated []struct {",
                "\tX int `json:\"x\"`",
                "}"
            ).joinToString("\n")
        )
    }

    @Test
    fun `number literals keep precision semantics`() {
        // 1.0 必须是 float64（不能被解析成整型）；超 Int 范围是 int64；空数组是 []any
        val out = convert("""{"n": 1.0, "big": 9999999999, "list": []}""")
        assertThat(out).isEqualTo(
            listOf(
                "type AutoGenerated struct {",
                "\tN    float64 `json:\"n\"`",
                "\tBig  int64   `json:\"big\"`",
                "\tList []any   `json:\"list\"`",
                "}"
            ).joinToString("\n")
        )
    }

    @Test
    fun `lenient parsing accepts trailing comma, single quotes and bare keys`() {
        val out = convert("{'a': 1,}")
        assertThat(out).contains("`json:\"a\"`")
        assertThat(convert("""{a: 1}""")).contains("A int")
    }

    @Test
    fun `parse error reports line number`() {
        val result = json_to_go_converter.convert("""{"a": }
{"b": 1}""", "Foo")
        assertThat(result.isFailure).isTrue()
        assertThat(result.exceptionOrNull()!!.message).contains("第 1 行")
    }

    @Test
    fun `scalar root is rejected`() {
        assertThat(json_to_go_converter.convert("\"hello\"").isFailure).isTrue()
        assertThat(json_to_go_converter.convert("null").isFailure).isTrue()
    }

    @Test
    fun `custom struct name is sanitized and exported`() {
        assertThat(convert("""{"a":1}""", "my config-v2")).startsWith("type MyConfigV2 struct {")
        assertThat(convert("""{"a":1}""", "2fast")).startsWith("type Num2fast struct {")
        assertThat(convert("""{"a":1}""", "   ")).startsWith("type AutoGenerated struct {")
    }

    @Test
    fun `null and mixed arrays`() {
        val out = convert("""{"maybe": [null, "a"], "weird": [[1, "x"], [2]]}""")
        assertThat(out).isEqualTo(
            listOf(
                "type AutoGenerated struct {",
                "\tMaybe []string `json:\"maybe\"`",
                "\tWeird [][]any  `json:\"weird\"`",
                "}"
            ).joinToString("\n")
        )
    }
}
